### ISSUE TITLE
Issue connecting when using django restframework

### ISSUE THREAD

**Issue by bryantmakesprog** [Kocal/django-tornado-websockets#2]
Following the documentation I've created the `/echo` handler.

I have an angular application and am trying to connect like so:

`$rootScope.websocket = $websocket.$new('ws://127.0.0.1:1717');`

So far so good.

When I connect, though, I see this error:

`WebSocket connection to 'ws://127.0.0.1:1717/' failed: Error during WebSocket handshake: Unexpected response code: 404`

And in my shell I can see this error repeated:

`Not Found: / 2018-01-11 16:41:03,636 [WARNING] django.request(L182): Not Found: /`

I've tried changing the url for the connection to `ws://127.0.0.1:1717/echo` but no luck either.

could you advise? Thanks!

**Comment by bryantmakesprog** [comment]
**Tornado Config**

```
# Tornado Config
import tornado_websockets
TORNADO = {
    'port': 1717,    # 8000 by default
    'handlers': [
        tornado_websockets.django_app(),  # django_app is using a "wildcard" route, so it should be the last element
    ],  # [] by default
    'settings': {
        'debug': True
    },  # {} by default
}
```

**Socket Info**

```
from tornado_websockets.websocket import WebSocket

# Create websocket.
ws_echo = WebSocket('/echo')

@ws_echo.on
def open(socket):
    # Notify all clients about a new connection
    ws_echo.emit('new_connection')

@ws_echo.on
def message(socket, data):
    # Reply to the client
    socket.emit('message', data)

    # Wow we got a spammer, let's inform the first client :^)
    if 'spam' in data.message:
        # wow
        ws_echo[0].emit('got_spam', {
            'message': data.get('message'),
            'socket': socket
        })
```

**Comment by bryantmakesprog** [comment]
Now through experimenting I've found that registering a `echo` route removes the 404, but doesn't make things work as expected.

**Comment by bryantmakesprog** [comment]
**Sample Log**

```
runtornado: Configuration => Found.
runtornado: Port => 1717.
runtornado: Handlers => Found 1 initial handlers.
runtornado: Settings => {"debug": true}
Not Found: /
2018-01-11 16:52:55,763 [WARNING] django.request(L182): Not Found: /
Not Found: /
2018-01-11 16:52:58,866 [WARNING] django.request(L182): Not Found: /
Not Found: /
2018-01-11 16:53:03,838 [WARNING] django.request(L182): Not Found: /
Not Found: /
2018-01-11 16:53:06,374 [WARNING] django.request(L182): Not Found: /
Not Found: /
2018-01-11 16:53:10,432 [WARNING] django.request(L182): Not Found: /
Not Found: /
2018-01-11 16:53:13,321 [WARNING] django.request(L182): Not Found: /
Not Found: /
2018-01-11 16:53:15,796 [WARNING] django.request(L182): Not Found: /
Not Found: /
2018-01-11 16:53:17,600 [WARNING] django.request(L182): Not Found: /
Not Found: /
2018-01-11 16:53:19,910 [WARNING] django.request(L182): Not Found: /
```

**Comment by Kocal** [comment]
Hello :)

Have you followed this [step](http://django-tornado-websockets.readthedocs.io/en/stable/django_integration_configuration.html#integration)?

I'm pretty sure your problem come from this

**Comment by bryantmakesprog** [comment]
Yes, I’m currently using the Django app handler. The tornado server seems to be recognizing calls made against it, it’s just not performing the echo when pinged.

On Jan 12, 2018, at 12:53 AM, Hugo Alliaume <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello :)

Have you followed this step<http://django-tornado-websockets.readthedocs.io/en/stable/django_integration_configuration.html#integration>?

I'm pretty sure your problem come from this

**Comment by Kocal** [comment]
Which version of Python and Django do you use?
